In [1]:
# Dependencies
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Google API Key
from localenv import gkey

In [2]:
types_df = pd.read_csv("ethnic_restr.csv")
types_df.head()

  ethnicity
0   chinese
1     cuban
2     czech
3    french
4    german

In [3]:
# set up additional columns to hold information
types_df['name'] = ""
types_df['address'] = ""
types_df['price_level'] = ""
types_df['rating'] = ""

types_df.head()

  ethnicity name address price_level rating
0   chinese
1     cuban
2     czech
3    french
4    german

## check out pandas.DataFrame.at
It's faster than .loc; similarly; .iat is faster than .iloc

[Pandas documentation about .loc and .at](https://pandas.pydata.org/pandas-docs/stable/indexing.html)

>Fast scalar value getting and setting
Since indexing with [] must handle a lot of cases (single-label access, slicing, boolean indexing, etc.), it has a bit of overhead in order to figure out what you’re asking for. If you only want to access a scalar value, the fastest way is to use the at and iat methods, which are implemented on all of the data structures.

>Similarly to loc, at provides label based scalar lookups, while, iat provides integer based lookups analogously to iloc


Check out this [speed test of .loc and .at (it's in castellano!)](http://pyciencia.blogspot.com/2015/05/obtener-y-filtrar-datos-de-un-dataframe.html)

In [10]:
# find the closest restaurant of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "location": "37.7913273,-122.3957994",  # 160 spear street san francisco
    "rankby": "distance",
    "type": "restaurant",
    "key": gkey,
}
# use iterrows to iterate through pandas dataframe
for index, row in types_df.iterrows():

    # get restaurant type from df
    restr_type = row['ethnicity']

    # add keyword to params dict
    params['keyword'] = restr_type

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {restr_type}.")
    response = requests.get(base_url, params=params).json()
    results = response.get('results')
    
    # extract first result and use pd.set_value to insert into dataframe
    results = response.get('results')
    if (results):
        restr = response['results'][0]
        print(f"Closest {restr_type} restaurant is {restr.get('name', 'Unknown')}.")
        types_df.at[index, 'name'] = restr.get('name', '')
        types_df.at[index, 'address'] = restr.get('vicinity', '')
        types_df.at[index, 'price_level'] = restr.get('price_level', '')
        types_df.at[index, 'rating'] = restr.get('rating', '')
    else:
        print("No results for " + restr_type)
    print("------------")

Retrieving Results for Index 0: chinese.
Closest chinese restaurant is Yank Sing (Spear Street).
------------
Retrieving Results for Index 1: cuban.
Closest cuban restaurant is Velvet Room.
------------
Retrieving Results for Index 2: czech.
Closest czech restaurant is Cafe Prague.
------------
Retrieving Results for Index 3: french.
Closest french restaurant is Cafe Bastille.
------------
Retrieving Results for Index 4: german.
Closest german restaurant is Schroeder's.
------------
Retrieving Results for Index 5: greek.
Closest greek restaurant is Locali Mediterranean.
------------
Retrieving Results for Index 6: haitian.
Closest haitian restaurant is Palm House.
------------
Retrieving Results for Index 7: hungarian.
Closest hungarian restaurant is Cafe Prague.
------------
Retrieving Results for Index 8: indian.
Closest indian restaurant is Muskaan Cuisine of India.
------------
Retrieving Results for Index 9: indonesian.
Closest indonesian restaurant is Borobudur Restaurant.
------------
Retrieving Results for Index 10: irish.
Closest irish restaurant is Harrington's Bar and Grill.
------------
Retrieving Results for Index 11: israeli.
Closest israeli restaurant is Wise Sons Jewish Delicatessen.
------------
Retrieving Results for Index 12: italian.
Closest italian restaurant is Americano.
------------
Retrieving Results for Index 13: japanese.
Closest japanese restaurant is Tokyo Express.
------------
Retrieving Results for Index 14: jewish.
Closest jewish restaurant is Wise Sons Jewish Delicatessen.
------------
Retrieving Results for Index 15: korean.
Closest korean restaurant is Sorabol BBQ Restaurant.
------------
Retrieving Results for Index 16: lebanese.
Closest lebanese restaurant is Oasis Grill.
------------
Retrieving Results for Index 17: mexican.
Closest mexican restaurant is Cantina Verde.
------------
Retrieving Results for Index 18: new american.
Closest new american restaurant is The Hideaway.
------------
Retrieving Results for Index 19: pakistani.
Closest pakistani restaurant is Raavi North Indian Cuisine.
------------
Retrieving Results for Index 20: polish.
Closest polish restaurant is Cafe Prague.
------------
Retrieving Results for Index 21: russian.
Closest russian restaurant is Pushkin.
------------
Retrieving Results for Index 22: scandinavian.
Closest scandinavian restaurant is Pläj Restaurant.
------------
Retrieving Results for Index 23: scottish.
No results for scottish
------------
Retrieving Results for Index 24: soul food.
Closest soul food restaurant is Hops & Hominy.
------------
Retrieving Results for Index 25: spanish.
Closest spanish restaurant is B44 Catalan Bistro.
------------
Retrieving Results for Index 26: thai.
Closest thai restaurant is Osha Express.
------------
Retrieving Results for Index 27: turkish.
Closest turkish restaurant is Barcha.
------------
Retrieving Results for Index 28: ukrainian.
Closest ukrainian restaurant is Pushkin.
------------
Retrieving Results for Index 29: vietnamese.
Closest vietnamese restaurant is Perilla.
------------

In [11]:
types_df

,ethnicity,name,address,price_level,rating
0,chinese,Yank Sing (Spear Street),"101 Spear St, San Francisco",2,4.2
1,cuban,Velvet Room,"495 Geary St, San Francisco",3,3.8
2,czech,Cafe Prague,"424 Merchant St, San Francisco",2,4.2
3,french,Cafe Bastille,"22 Belden Pl, San Francisco",3,4.2
4,german,Schroeder's,"240 Front St, San Francisco",2,4
5,greek,Locali Mediterranean,"98 Battery St, San Francisco",,4.1
6,haitian,Palm House,"2032 Union St, San Francisco",2,4.3
7,hungarian,Cafe Prague,"424 Merchant St, San Francisco",2,4.2
8,indian,Muskaan Cuisine of India,"101 Spear St A23, San Francisco",1,2.6
9,indonesian,Borobudur Restaurant,"700 Post St, San Francisco",2,4.2
10,irish,Harrington's Bar and Grill,"245 Front St, San Francisco",1,3.8
11,israeli,Wise Sons Jewish Delicatessen,"1 Embarcadero Drive, San Francisco",1,5
12,italian,Americano,"8 Mission St, San Francisco",2,3.9
13,japanese,Tokyo Express,"160 Spear St, San Francisco",1,4
14,jewish,Wise Sons Jewish Delicatessen,"1 Embarcadero Drive, San Francisco",1,5
15,korean,Sorabol BBQ Restaurant,"RINCON CENTER, 101 Spear St A-12, San Francisco",1,3.5
16,lebanese,Oasis Grill,"91 Drumm St, San Francisco",1,4.4
17,mexican,Cantina Verde,"Corner of Front St. & Pine St., San Francisco",,4.4
18,new american,The Hideaway,"5634 College Ave, Oakland",,4.2
19,pakistani,Raavi North Indian Cuisine,"533 Jackson St, San Francisco",,4.2
20,polish,Cafe Prague,"424 Merchant St, San Francisco",2,4.2
21,russian,Pushkin,"380 Bush St, San Francisco",1,4.6
22,scandinavian,Pläj Restaurant,"333 Fulton St, San Francisco",3,4.6
23,scottish,Martins West Gastropub,"831 Main St, Redwood City",3,4.3
24,soul food,Hops & Hominy,"1 Tillman Pl, San Francisco",2,4.3
25,spanish,B44 Catalan Bistro,"44 Belden Pl, San Francisco",3,4
26,thai,Osha Express,"One Market Plaza, #21b, San Francisco",,4.1
27,turkish,Barcha,"28 Fremont St., San Francisco",3,4.3
28,ukrainian,Pushkin,"380 Bush St, San Francisco",1,4.6
29,vietnamese,Perilla,"510 Mission St, San Francisco",1,4.2